### ISSUE TITLE
Backups broken due to mongoctl/pymongo incompatibility

### ISSUE THREAD

**Issue by davidwilemski** [davidwilemski/openrunlog#78]
```
Traceback (most recent call last):
  File "/home/david/orl_env/bin/mongoctl", line 48, in <module>
    from mongoctl import mongoctl
  File "/home/david/orl_env/local/lib/python2.7/site-packages/mongoctl/mongoctl.py", line 56, in <module>
    from pymongo import Connection
ImportError: cannot import name Connection
```

**Comment by davidwilemski** [comment]
fixed in aedb3bb9b0c7a70680d06c30b27b8740631299ba
